# Create Database
# ------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS apigatewaydb DEFAULT CHARACTER SET = utf8mb4;
CREATE DATABASE IF NOT EXISTS uaadb DEFAULT CHARACTER SET = utf8mb4;
CREATE DATABASE IF NOT EXISTS rmsvcdb DEFAULT CHARACTER SET = utf8mb4;
CREATE DATABASE IF NOT EXISTS hmsvcdb DEFAULT CHARACTER SET = utf8mb4;
CREATE DATABASE IF NOT EXISTS mdatasvcdb DEFAULT CHARACTER SET = utf8mb4;
CREATE DATABASE IF NOT EXISTS rulesvcdb DEFAULT CHARACTER SET = utf8mb4;