FROM node:8

LABEL authors="fangheng <9773659@qq.com>"

WORKDIR /usr/src/app

COPY package.json package.json

RUN npm config set registry https://registry.npm.taobao.org \
    && npm i

COPY . .

RUN npm run ngBuild
