version: '2'
services:
    rlsoms-apigateway-app:
        image: rlsoms-apigateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger,no-liquibase
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@rlsoms-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@rlsoms-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://rlsoms-mysql-db:3306/apigatewaydb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=CrrcZnyw            
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
        ports:
            - 8080:8080

    registry:
        image: rlsoms-registry
        volumes:
            - ./central-server-config:/central-config
        # When run with the "dev" Spring profile, the JHipster Registry will
        # read the config from the local filesystem (central-server-config directory)
        # When run with the "prod" Spring profile, it will read the configuration from a Git repository
        # See http://www.jhipster.tech/microservices-architecture/#registry_app_configuration
        environment:
            - SPRING_PROFILES_ACTIVE=native
            - SECURITY_USER_PASSWORD=admin
            - JHIPSTER_REGISTRY_PASSWORD=admin
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
            - GIT_SEARCH_PATHS=central-config
        ports:
            - 8761:8761

    uaa-app:
        image: uaa
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger,no-liquibase
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@rlsoms-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@rlsoms-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:mysql://rlsoms-mysql-db:3306/uaadb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=CrrcZnyw            
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application

    rlsoms-mysql-db:
        image: mysql:5.7.20
        volumes:
            - /opt/mysql/db/:/var/lib/mysql/
            - ./sql:/docker-entrypoint-initdb.d    
        environment:
            - MYSQL_USER=root
            - TZ=Asia/Shanghai
   #         - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=CrrcZnyw
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
